---
output: 
  html_document: 
    highlight: textmate
    theme: yeti
    toc: yes
---

Merge tree file with the phyloseq object
```{r, warning=FALSE, echo=T, error=F, message=F, cache=T}
library(tidyverse)
library(phyloseq)
library(ggtree)
library(ggplot2)

tree <- read.tree("data/tree.nwk")
tree

inc_phy <- readRDS("data/RDS/incubation_physeq_Aug18.RDS")

# Add the tree file to the phyloseq object
inc_phy <- merge_phyloseq(inc_phy, tree)
inc_phy
```

Subset the object to incubated samples and rename some variables and rarefy to 6,000 based on 
rarefactioncurve.R
```{r, warning=FALSE, echo=T, error=F, message=F, cache=T}

#subset
inc.physeq <- subset_samples(inc_phy, day %in% c("7",
                                                        "14",
                                                        "21",
                                                        "35",
                                                        "49",
                                                        "97"))

#Rename treatments to more informative titles
data <- data.frame(sample_data(inc.physeq)) %>%
  mutate(treatment = recode(treatment,
                            'Control' = 'Reference',
                            'CompAlfa' = 'Mix')) %>%
  mutate(C_N = C_flash / N_flash, Inorganic_N = NH3 + NO3) %>%
  mutate(TreatmentAndDay = paste(treatment, day))
rownames(data) <- data$i_id
sample_data(inc.physeq) <- data
sample_data(inc.physeq)$day <- as.factor(sample_data(inc.physeq)$day)
head(sample_data(inc.physeq))

# Rarefy
rare6k.physeq <- rarefy_even_depth(inc.physeq, sample.size = 6000,
                                   rngseed = 15879966) %>%
  filter_taxa(function(x) sum(x) >= 2, T) 
  
```

Now let's plot an PCA ordination of the weighted unifrac distances, which uses the phylogenetic tree and considers the phylogenetic relationship between OTUs when calculating the distance matrix
```{r, cache=T, warning=F, message=F}
PCoA <- ordinate(rare6k.physeq, "PCoA", "wunifrac")
plot_ordination(rare6k.physeq, PCoA, color = "day") + stat_ellipse(geom = "polygon", type = "norm", alpha = 0.2, aes(fill = day))
```
```{r, cache=T, warning=F, message=F}
NMDS <- ordinate(rare6k.physeq, "NMDS", "wunifrac")
plot_ordination(rare6k.physeq, NMDS, color = "day") + stat_ellipse(geom = "polygon", type = "norm", alpha = 0.2, aes(fill = day))
```

```{r}

```


