---
title: "test"
author: "Jared Flater"
date: "5/15/2019"
output:
  html_document:
    df_print: paged
    fig_width: 8.5
    fig_height: 11
    fig_caption: true
    toc: true
    number_sections: false
---

```{r, echo = F, message = F, warning = F}
knitr::opts_chunk$set(echo = TRUE)
# if (!requireNamespace("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# 
# BiocManager::install("ggtree")
# BiocManager::install("phyloseq")
# BiocManager::install("treeio")

library(reshape2)
library(tidyverse)
library(phyloseq)
library(ggtree)
library(treeio)
library(viridis)
library(phylosmith)
library(kableExtra)
```
```{r, message=F, error=F, warning=F, echo=F}
tree <- read.tree("../data/tree.nwk")
inc.physeq <- readRDS("../data/RDS/incubation_physeq_Aug18.RDS")
inc <- merge_phyloseq(inc.physeq, tree)
inc <- subset_samples(inc, day %in% c("7", "14", "21", "35", "49", "97"))

no.unclass <- subset_taxa(inc, !Phylum=="Bacteria_unclassified")
no.unclass <- subset_taxa(no.unclass, !Genus=="Gp6_unclassified")
inc_rare <- rarefy_even_depth(physeq = no.unclass, sample.size = 5000, rngseed = 3242343, verbose = F)
 
```
 
# This tree is showing comparisons between amendment and reference, the previous example showed differences between amendment and reference plus amendment from the previous time point. This should be a more accurate representation of OTUs responding to the amendment for each 

```{r, message=F, error=F, warning=F, echo=F}
# RDS saved from Alfalfa_Deseq, Mix_Deseq, Compost_Deseq
resp_alf <- readRDS("../data/RDS/LFC_alf_OTUs_June19.RDS") %>% dplyr::rename(label = OTU)
resp_comp <- readRDS("../data/RDS/LFC_comp_OTUs_June19.RDS") %>% dplyr::rename(label = OTU)
resp_mix <- readRDS("../data/RDS/LFC_mix_OTUs_June19.RDS") %>% dplyr::rename(label = OTU)

resp <- rbind(resp_alf[1], resp_comp[1], resp_mix[1])

dist_all_resp <- distinct(resp)

df <- resp_alf %>%
  full_join(resp_comp) %>%
  full_join(resp_mix)
```
```{r, message=F, error=F, warning=F, echo=F}
inc_resp <- prune_taxa(c(df$label), inc_rare)
```
```{r, message=F, error=F, warning=F, echo=F}
inc_resp <- phy_tree(inc_resp)
inc_resp
```
```{r, message=F, error=F, warning=F, echo=F}
df2 = dplyr::mutate(df, newlab = paste(label, Phylum, Genus, sep='|'))
head(df2)
```
```{r, message=F, error=F, warning=F, echo=F}
resp_p <- ggtree(inc_resp) %<+% df2 +
  geom_tiplab(aes(label=newlab), size=1, align=TRUE, linesize=.1) + theme_tree() 
```
```{r, message=F, error=F, warning=F, echo=F}

colnames(df2)
head(df2$label)

df3 <- df2 %>%
  select(label, Alfalfa_early_log2FoldChange, Mix_early_log2FoldChange, Compost_early_log2FoldChange, Alfalfa_late_log2FoldChange, Mix_late_log2FoldChange, Compost_late_log2FoldChange) %>%
  column_to_rownames(var = "label")

write.csv(df3, file ="../data/resp_table.csv")
```
```{r, message=F, error=F, warning=F, echo=F}
final_resp <- resp_p  %>% 
  gheatmap(df3, offset=0.25, width=0.1, font.size = 1, colnames=T, colnames_angle=-45, hjust=0, color = "black") +
  ggtitle("Log fold change of genera for each treatment response group")
plot(final_resp) + scale_fill_viridis(option = "plasma") + ggplot2::theme_dark() +
  guides(fill=guide_legend(title="Log fold change"))
#plot(final_resp) + scale_color_viridis(discrete = T, option = "viridis") + ggplot2::theme_bw()
png("../Figures/resp_tree.png", height = 20, width = 14, units = 'in', res = 600)
plot(final_resp) + scale_fill_viridis(option = "plasma") + ggplot2::theme_dark() +
  guides(fill=guide_legend(title="Log fold change"))
dev.off()
```
```{r, message=F, error=F, warning=F, echo=F}
# Common responders in all amendments and response groups
new_DF <- df3[rowSums(is.na(df3)) == 0,]
kable(new_DF) %>%
  kable_styling(bootstrap_options = "striped") %>%
  scroll_box(width = "100%", height = "400px")

# Plot relative abundance by treatment across days for the 441 responding OTUs
# phph <- subset_taxa(inc_rare, rownames(tax_table(inc_rare)) %in% dist_all_resp$label)
# phph.r <- phph %>%
#   transform_sample_counts(function(x) x / sum(x)) %>%
#   psmelt()
# ggplot(data = phph.r, mapping = aes(x = day, y = Abundance, color = OTU)) +
#   geom_bar(stat = "identity") +
#   facet_wrap("treatment") +
#   theme(legend.position = "none")
```

